# Deployment for microservice-a
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-a
  labels:
    app: microservice-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-a
  template:
    metadata:
      labels:
        app: microservice-a
    spec:
      containers:
        - name: app
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: shared-efs
              mountPath: /usr/share/nginx/html
      volumes:
        - name: shared-efs
          persistentVolumeClaim:
            claimName: efs-pvc
