# Standalone Prometheus scrape configuration reference
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: microservice-a
    metrics_path: /metrics
    static_configs:
      - targets: ['microservice-a.default.svc.cluster.local:80']
  - job_name: microservice-b
    metrics_path: /metrics
    static_configs:
      - targets: ['microservice-b.default.svc.cluster.local:80']
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
