# Deployment for microservice-b
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-b
  labels:
    app: microservice-b
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservice-b
  template:
    metadata:
      labels:
        app: microservice-b
    spec:
      containers:
        - name: app
          image: public.ecr.aws/amazonlinux/amazonlinux:latest
          ports:
            - containerPort: 8081
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: url
          volumeMounts:
            - name: efs
              mountPath: /mnt/data
      volumes:
        - name: efs
          persistentVolumeClaim:
            claimName: efs-pvc
