apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: {{ .Values.prometheus.namespace }}
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: microservice-a
        static_configs:
          - targets: ['microservice-a.default.svc.cluster.local:80']
      - job_name: microservice-b
        static_configs:
          - targets: ['microservice-b.default.svc.cluster.local:80']
      - job_name: prometheus
        static_configs:
          - targets: ['localhost:9090']
