# Deployment for microservice-b
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-b
  labels:
    app: microservice-b
spec:
  replicas: 3
  selector:
    matchLabels:
      app: microservice-b
  template:
    metadata:
      labels:
        app: microservice-b
    spec:
      containers:
        - name: microservice-b
          image: nginx:latest
          ports:
            - containerPort: 80
